### ISSUE TITLE
The error with assembly_accession key

### ISSUE THREAD

**Issue by lm-jkominek** [neoLIZV/neoHGT#1]
Hi, just wanted to say that NeoHGT broke because of the recent NCBI format change, that affect HGTector as well:

https://github.com/qiyunlab/HGTector/issues/123

**Comment by neoLIZV** [comment]
Thank you very much for your message!

The patch has been implemented.
Cheers :)

_______________________________________
Steps to reinstall neoHGT to fetch the update:

`conda activate neoHGT`
`pip uninstall neoHGT `
`pip install git+https://github.com/neoLIZV/neoHGT.git`

**Comment by lm-jkominek** [comment]
Of course, happy to help!
